### ISSUE TITLE
How to add code in Markdown?

### ISSUE THREAD

**Issue by pratikwatwani** [tash-had/leetcode-buddy#1]
Is there a way to add your own code in Markdown or code format?

It will be useful if I am just looking at notes and decide to print them in future!

**Comment by tash-had** [comment]
Thanks for the request @pratikwatwani. Just added the ability to add code blocks to your notes. Submitted the update now, it should take about a day to get through the review process.

![image](https://user-images.githubusercontent.com/5132330/97841619-355e5e00-1cb4-11eb-96f3-ccc46043bbba.png)

**Comment by pratikwatwani** [comment]
> Thanks for the request @pratikwatwani. Just added the ability to add code blocks to your notes. Submitted the update now, it should take about a day to get through the review process.
> 
> ![image](https://user-images.githubusercontent.com/5132330/97841619-355e5e00-1cb4-11eb-96f3-ccc46043bbba.png)

Thanks @tash-had, this would definitely help! Just a future update suggestion, maybe you could add Markdown capabilities?
